version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: rediis
  application:
    image: my_application
    build: .
    container_name: application
    links:
      - redis:rediis
    depends_on:
      - redis

    