version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    hostname: redis
  application:
    image: my_application
    build: .
    container_name: application
    depends_on:
      - redis
    links:
      - redis

    